spring:
  datasource:
    username: wreczyck
    password: <password>
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=wreczyck
  sql:
    init:
      mode: always
  flyway:
    user: wreczyck
    password: <password>
    url: jdbc:sqlserver://morfeusz.wszib.edu.pl:1433;databaseName=wreczyck
    locations: classpath:db/migrations
    schemas: [wreczyck]
    enabled: false
